#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$(dirname "$HOOKS_DIR")"
cd $DIR

npm run lint-staged